### ISSUE TITLE
The opposite of RECS0129, RECS0145, ...

### ISSUE THREAD

**Issue by axelheer** [icsharpcode/RefactoringEssentials#41] opened 2015-07-24 19:37 UTC
These rules suggest to remove unnecessary access modifiers, which sounds reasonable and I don't want to start a discussion about having them or not.

But, *coding styles* like the one of [.NET Core](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md), just to name a prominent project, often require to include them, which sounds reasonable too -- it seems to be solely opinion based.

Thus, it would be nice to have both options including some kind of configuration, ideally at global and project level.

**Comment by christophwille** [comment] 2015-07-25 15:20
I agree that the duals would have their place, but the problem is both would be activated by default (until one sets up a rule set). That's a problem I don't see how we could overcome it.

**Comment by axelheer** [comment] 2015-07-25 18:29
Yeah, having both activated would be odd.

**Comment by christophwille** [comment] 2015-07-28 07:55
As there is no way to ship with one of the two enabled, we will close this issue for now.

**Closed by christophwille** 2015-07-28 07:55 UTC

**Comment by newsash** [comment] 2015-08-06 08:09
How about action Hidden or None by default?

**Comment by iccfish** [comment] 2015-08-28 16:21
I totally agree with @axelheer , as there are too many RECS0129/0145/0163 in error list and solution explorer. And I have no plan to modify the source codes due to the project was an old project with a suitable state or a third-party project (for ex, 130 errors on Dapper project), and the changes are really a heavy work but leads no effect on result.
In other words, I have to disable RE to avoid these 'errors'.

Still watching RE and hope there could have a configuration to turn rules on and off.

**Comment by newsash** [comment] 2015-08-28 16:47
@Rpinski has already fixed RECS0129/0145 in 5c295c9d05c2f9683ff17565e354d00c500afd67

**Comment by christophwille** [comment] 2015-08-28 16:51
@iccfish see https://github.com/icsharpcode/RefactoringEssentials/wiki/Custom-Rule-Sets-for-Analyzers

**Comment by iccfish** [comment] 2015-08-28 16:59
yeah ... I see, but extension for visual studio was released 21 days ago. should I try to build a nightly build and test again :smile:
