### ISSUE TITLE
misfiring rule RECS0130: 'for' loop control variable is never modified

### ISSUE THREAD

**Issue by AArnott** [icsharpcode/RefactoringEssentials#235] opened 2016-06-24 05:08 UTC
This rule misfires, until in the error list I navigate to it. Once the document is opened, the diagnostic always disappears.

One for loop it misfires on is this:

```c#
private const int StoreLockRetryCount = 100;
//...
   for (int tryCount = 0; tryCount < StoreLockRetryCount; tryCount++)
```

**Comment by patrickhuber** [comment] 2016-07-06 18:41
Looks like its in this analyzer: https://github.com/icsharpcode/RefactoringEssentials/blob/master/RefactoringEssentials/CSharp/Diagnostics/Synced/CodeQuality/ForControlVariableIsNeverModifiedAnalyzer.cs

**Comment by Rpinski** [comment] 2016-07-06 21:34
Unfortunately I haven't been able to reproduce it yet using your example.

**Comment by patrickhuber** [comment] 2016-07-07 22:52
I can't reproduce it with tests, but I have a way to reproduce with a simple Program.cs file and the following steps:

1. Close all files
2. Build > Rebuild Solution
3. Open View > Error List
4. Observe misfiring rule
5. Double click misfiring rule in Error List
6. Observe misfiring rule remains
7. Build > Rebuild Solution
8. Observe misfiring rule is gone

> Program.cs

```csharp
namespace ForControlVariableIsNeverModifiedAnalyzer
{
    class Program
    {
        static void Main(string[] args)
        {
            int[] tab1 = { 0, 1, 2, 3, 4 };
            for (var i = 0; i < tab1.Length - 1; i++)
            {

            }
        }
    }
}

```

Analyzer firing with file closed

![Analyzer firing with file closed](https://cloud.githubusercontent.com/assets/182398/16672193/8317ed7e-4472-11e6-8c1d-f8edc45e86e7.PNG)

Analyzer firing with file open pre rebuild

![Analyzer firing with file open pre rebuild](https://cloud.githubusercontent.com/assets/182398/16672217/a0bf20e0-4472-11e6-9431-707fdd77dcb7.PNG)

Analyzer not firing with file open after rebuild

![analyzer not firing with file open after rebuild](https://cloud.githubusercontent.com/assets/182398/16672234/bbb01cb0-4472-11e6-84bb-410368fd1913.PNG)

Visual Studio Version:

```
Microsoft Visual Studio Enterprise 2015
Version 14.0.25421.03 Update 3
Microsoft .NET Framework
Version 4.6.01038

Installed Version: Enterprise
```

Extension Version:

```
4.2.0.0
```

**Comment by patrickhuber** [comment] 2016-07-12 01:07
I managed to debug the vsix and found the source of the bug. It appears the analyzer makes two passes over the syntax tree. When the node context information for the semantic model is pulled

```csharp
... 
if(nodeContext.SemanticModel.GetSymbolInfo(identifier).Symbol == local){
...
```

The object references are compared instead of checking for equality. I suppose that the semantic model is different than the syntax node instance and this check fails on the second pass. 

Changing to using the Equals method allows the check to succeed on both passes. 

```csharp
... 
if(nodeContext.SemanticModel.GetSymbolInfo(identifier).Symbol.Equals(local)){
...
```
I have created and submitted a pull request with this fix.

**Comment by tanveerbadar** [comment] 2016-07-12 16:54
Experienced this issue, messages did not go away after opening documents, had to disable the extension entirely because of the huge number of false alarms causing high memory usage in VS.

**Comment by AArnott** [comment] 2016-07-12 18:01
Thanks for the fix, @patrickhuber

**Comment by Rpinski** [comment] 2016-07-12 21:05
Merged the pull request, Thanks to @patrickhuber!

**Closed by Rpinski** 2016-07-12 21:05 UTC

**Comment by SamuelEnglard** [comment] 2016-07-15 17:16
@tanveerbadar a better solution you can do is have VS always suppress this issue:

```csharp
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("", "RECS0130")]
```

**Comment by tanveerbadar** [comment] 2016-07-17 06:13
You are absolutely correct, honestly this solution never occurred to me.
